### ISSUE TITLE
Propose next index in case of duplicate codes

### ISSUE THREAD

**Issue by kaklakariada** [exasol/error-code-crawler-maven-plugin#66]
In case of duplicate error codes it would be helpful if the crawler could propose the next free index in the error message. This would make it easier to fix the problem without searching the complete code.

**Comment by jakobbraun** [comment]
The big plan for this is to maintain the highest error-code in the error-code-config.yml. In addition we planned to add a script that supplies the next free error-code + increases the number. Then we can add an integration to IDEs that past this by a certain key-combination.

**Comment by jakobbraun** [comment]
Searching for the next free one is problematic, since it would re-use error-codes that were removed.

**Comment by kaklakariada** [comment]
I would just propose `highest-index + 1`. Then the user does not have to look it up themselves
